### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by gentilinigm** [cartabinaria/csurename#10]
Aggiunta di Unit Tests vari che andranno poi integrati in un eventuale CI.

Al momento organizzerei i tests in questo modo:
.tests/
|-- modules/
|   |-- template.rs
|   |-- analisi.rs
|   \`-- ...
|-- integration_tests.rs
\`-- common.rs

-  _modules/_ => i vari insegnamenti con i loro regex e (default) template.
- _integration_tests.rs_ => i test piu' semplici ed esterni.
- _common.rs_ =>  funzioni condivise dai test.

Per i test dei regex si potrebbero usare proprio le pr fallite in passato.

Vari test piu avanzati (come ad esempio per #1 e #7) saranno poi discussi in altre issues o qui.

[Testing CLA in rust](https://rust-cli.github.io/book/tutorial/testing.html) un buono spunto.

I test dei moduli sono molto utili anche per controllare immediatamente se il rename e' andato a buon fine, senza far fallire una pull request.

**Comment by foxyseta** [comment]
Gli insegnamenti hanno tutte le regexp uguali tranne poche poche eccezioni (che potremmo batterci per eliminare in futuro). Avere un .rs per ogni insegnamento non genera molto codice boilerplate/duplicato?

**Comment by foxyseta** [comment]
Nel senso: se mettiamo tutto il codice in comune in common, possiamo semplicemente ciclare su tutti gli insegnamenti (tranne eventuali eccezioni) in un unico punto del codice.

**Comment by gentilinigm** [comment]
L'idea era di aggiungere solo quelli che cambiano ed usare sempre i regex di template negli altri casi, però se sono cosí pochi e stiamo cercando di toglierli si possono eliminare direttamente i moduli e farne uno solo.

**Comment by foxyseta** [comment]
Ahhh ok ho capito ora. Che io sappia sono 2 le eccezioni al momento (cybersicurezza nostra e vostra), quindi scegli tu come preferisci.

@crestaa confermi che solo di queste due hai cambiato le regexp? Hai solo impostato recursive a false o hai anche fatto altro?

**Comment by crestaa** [comment]
> @crestaa confermi che solo di queste due hai cambiato le regexp? Hai solo impostato recursive a false o hai anche fatto altro?

Fondamenti di cybersecurity ha solo la regexp modificata ma recursive è ancora a true, mentre laboratorio di sicurezza ha sia la regexp cambiata sia recursive a false, ma se volete eliminare questi casi specifici possiamo trovare un modo di salvare i file che si adatti a tutto il resto

**Comment by foxyseta** [comment]
Finora l'unico problema sono state le risorse "in allegato" alle prove.

Se le zippiamo, abbiamo un unico file per cui possiamo pensare a un nome solo rispettoso delle convenzioni, ma non possono essere più viste da browser web. Se le lasciamo così come sono, possono essere visualizzate da browser web, ma rinominarle tutte con i lunghissimi prefissi del nome della prova diventa scemo e snatura i nomi a cui il prof aveva pensato inizialmente.

Io proporrei di lasciare recursive sempre accesa come opzione ma di ignorare i contenuti delle cartelle che rispetano la regexp (senza estensione ovviamente). Così si salvano capra e cavoli.

**Comment by foxyseta** [comment]
Chiusa per sbaglio scusate.

**Comment by gentilinigm** [comment]
> Finora l'unico problema sono state le risorse "in allegato" alle prove.
> 
> Se le zippiamo, abbiamo un unico file per cui possiamo pensare a un nome solo rispettoso delle convenzioni, ma non possono essere più viste da browser web. Se le lasciamo così come sono, possono essere visualizzate da browser web, ma rinominarle tutte con i lunghissimi prefissi del nome della prova diventa scemo e snatura i nomi a cui il prof aveva pensato inizialmente.
> 
> Io proporrei di lasciare recursive sempre accesa come opzione ma di ignorare i contenuti delle cartelle che rispetano la regexp (senza estensione ovviamente). Così si salvano capra e cavoli.

Si concordo, si può cambiare in un flag --no-recursive magari.
Quando abbiamo le idee più chiare ne discutiamo su #6.

**Comment by foxyseta** [comment]
Aggiornamento: ho creato la repo https://github.com/csunibo/config e l'ho aggiunta come sottomodulo nella cartella config. Quindi in futuro sia csurename che tutte le repo rispetteranno le convenzioni nel json al suo interno, senza eccezioni. Se si vogliono modificare le regexp, lo si fa una sola volta dalla repo config originale.
