### ISSUE TITLE
Indice dei lucidi

### ISSUE THREAD

**Issue by foxyseta** [cartabinaria/csurename#2]
Forzare il kebab case non è abbastanza: nel caso dei lucidi, bisogna anche indovinare un papabile prefisso numerico

**Comment by lucat1** [comment]
Roba simile a quella che devo fare per taggare la musica. Secondo me il prefisso andrebbe controllato con questa euristica:
1. Prendiamo il prefisso da ogni file nella cartella, leggendoli come interi nelle variabili $p_1, \ldots, p_n$.
2. $max_{pad} = \lceil log_{10}(max(p_1, \ldots, p_n)) \rceil$
3. il file $i$ deve iniziare con $repeat(max_{pad} - \lfloor log_{10}(p_i) \rfloor, 0)$ concatenato a $i$ in base 10. $repeat(times, value)$ crea una stringa concatenando $value$ $times$ volte.

Penso che quello che ho scritto funzioni, ma controlla magari. Gli zeri davanti ai nomi sono necessari per fare in modo che il sorting sia corretto, altrimenti `10` verrebbe prima di `1`.
Il vero problema secondo me è come esprimere tramite le regexp che vogliamo applicare questo controllo. In rust sai se si può estendere il parser delle regexp con una nuova "regola". E anche una volta fatto, sarebbe una regola difficile da applicare se la cartella contiene qualche file che non dovrebbe essere avere la numerazione. Ho qualche perplessità sul come applicare questa cosa, te ci avevi pensato a fondo?
