### ISSUE TITLE
Rimuovere gli accenti

### ISSUE THREAD

**Issue by foxyseta** [cartabinaria/csurename#5]
Nelle regex non accettiamo mai accenti e altri segni grafici non alfanumerici (a meno che non sia il trattino classico). `csurename` dovrebbe rimuoverli tutti, possibilmente sostituendoli con le loro controparti "semplici". Vista la enorme quantità di caratteri speciali di questo tipo, è altamente preferibile trovare un pacchetto specializzato che lo faccia per noi.

**Comment by gentilinigm** [comment]
Riguardo gli accenti, [unicode_normalization](https://docs.rs/unicode-normalization/latest/unicode_normalization/) sembra essere un ottimo create, implementa la [Unicode Normalization Form KD ](https://www.unicode.org/reports/tr15/#Norm_Forms), che é molto vicino a quello che vogliamo fare, ma questa non toglie molti altri caratteri unicode che non sono compatibili con i soliti regex (credo?).
Ad esempio, la stringa "A Α А Ꭺ ᗅ ᴀ ꓮ Ａ 𐊠 𝐀 𝐴 𝑨 𝒜 𝓐 𝔄 𝔸 𝕬 𝖠 𝗔 𝘈 𝘼 𝙰 𝚨 𝛢 𝜜 𝝖 𝞐"
viene convertita a: "A Α А Ꭺ ᗅ ᴀ ꓮ A 𐊠 A A A A A A A A A A A A A Α Α Α Α Α".

Ci sono diverse possiblità, per ora ho trovato queste 2:
- Normalizziamo secondo la forma KD e rimuoviamo direttamente tutti quegli altri caratteri problematici che sono comunque molto rari e probabilmente mai necessari.
- Usiamo il Crate [deunicode](https://crates.io/crates/deunicode), che farebbe più al caso nostro, ma potrebbe essere un po' un overkill in questo caso.

Qualcuno ha qualche altra idea?
Dite che é anche il caso di aggiungere un flag per non effettuare questa conversione? (Questo se mai si presenteranno casi che richiedono caratteri speciali in futuro).

**Comment by foxyseta** [comment]
A me sembra overkill pure la prima quindi fra le due andrei su quella. Finora abbiamo avuto test falliti solo per accenti o apostrofi o punteggiatura, e mai per altro.

**Comment by gentilinigm** [comment]
Meno del primo che io sappia c'é giusto la [NFD](https://www.unicode.org/reports/tr15/#Norm_Forms), sempre disponibile nel crate [unicode_normalization](https://docs.rs/unicode-normalization/latest/unicode_normalization/).

A parte qualcuno voglia aggiungere un file in cinese basta e avanza quella... comunque se avete qualche altra idea é ben accetta.
